# Generated by Django 2.2.1 on 2019-05-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='Project Title', max_length=140),
            preserve_default=False,
        ),
    ]
